version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpcms
      MYSQL_USER: patrick
      MYSQL_PASSWORD: password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - $PWD:/var/www/wordpress
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: patrick
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wpcms

  workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: workbench
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "3000:3000"
    cap_add:
      - IPC_LOCK

volumes:
  db_data: {}
